"""followers

Revision ID: 721790c63d50
Revises: 499408602dd4
Create Date: 2019-07-09 15:44:06.923514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721790c63d50'
down_revision = '499408602dd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
